version: '3'
networks:
  kafka_network:
    driver: bridge
services:
  zookeeper:
    networks:
      - kafka_network
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: on-failure

  kafka:
    networks:
      - kafka_network
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 60000
    restart: on-failure

  python_app:
    build: ./python_app
    depends_on:
      - kafka

    networks:
      - kafka_network
